id: A3857E433
base_file: f4F9F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:05:13.025473
  last_modified_at: 2022-06-05 20:05:13.025481
